spring.application.name=SB-SMS-SERVICE
server.port = 1118

#Database Properties
spring.datasource.url=jdbc:mysql://localhost:3306/supplier_db
spring.datasource.username=root
spring.datasource.password=Saud231005@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.instance.hostname=localhost

#Stop registering as a client. It is a Server
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

#Appication Properties
sms.save.success  = "SUCCES : Supplier Object Saved"
sms.save.failed = "FAILED : DB Error"
sms.update.success = "SUCCESS : Supplier Object Updated" 

sms.delete.success  = "SUCCES : Supplier Object deleted"
sms.delete.failed = "FAILED : Id cannot Be Found"

sms.get.failed = "FAILED : Id cannot be found"
sms.findall.fail ="FAILED : No Products"


sms.db.failed = "FAILED : DB Error"

sms.getname.failed = "FAILED : Name cannot be found"

ems.invalid.employee-notfound = "FAILED : Supplier Not Found"