spring.application.name=SB-EMS
# embedded tomcat server port number
server.port = 1234 

#Database Properties
spring.datasource.url=jdbc:mysql://localhost:3306/db_employee
spring.datasource.username=root
spring.datasource.password=Saud231005@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Appication Properties
ems.save.success  = "SUCCES : Employee Object Saved"
ems.save.failed = "FAILED : DB Error"
ems.update.success = "SUCCESS : Employee Object Updated" 

ems.delete.success  = "SUCCES : Employee Object deleted"
ems.delete.failed = "FAILED : Id cant Be Found"

ems.get.failed = "FAILED : Id cant be found"
ems.findall.fail ="FAILED : No Employees"


ems.db.failed = "FAILED : DB Error"


ems.getname.failed = "FAILED : Name cant be found"

ems.invalid.employee-notFound  = "FAILED : Employee Not Found"